import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import HeaderBar from "@/components/header/HeaderBar";
import HeaderColoredSurrounding from "@/components/header/HeaderColoredSurrounding";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
